CREATE DATABASE OPTUS
GO

USE OPTUS
GO

CREATE TABLE ARTISTA (
	idArtista SMALLINT PRIMARY KEY IDENTITY,
	nomeArtista VARCHAR(30) NOT NULL,
);
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY,
	nome VARCHAR(25) NOT NULL,
	permissao TINYINT NOT NULL,
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE ESTILO (
	idEstilo SMALLINT PRIMARY KEY IDENTITY,
	nomeEstilo VARCHAR(20) NOT NULL,
);

CREATE TABLE ALBUM (
	idAlbum SMALLINT PRIMARY KEY IDENTITY,
	idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA (idArtista),
);
GO

ALTER TABLE ALBUM
ADD titulo VARCHAR(30)

ALTER TABLE ALBUM
ADD dataLancamento SMALLDATETIME 

ALTER TABLE ALBUM
ADD localizacao VARCHAR(40)

ALTER TABLE ALBUM 
ADD minutosDuracao SMALLINT

ALTER TABLE ALBUM
ADD disponibilidade TINYINT
GO

CREATE TABLE ALBUM_ESTILO (
	idAlbumEstilo SMALLINT PRIMARY KEY IDENTITY,
	idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM (idAlbum),
	idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO (idEstilo)
);
GO