CREATE DATABASE OPTUS
GO

USE OPTUS
GO

CREATE TABLE ARTISTA (
	idArtista SMALLINT PRIMARY KEY IDENTITY,
	nomeArtista VARCHAR(30) NOT NULL,
);
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY,
	nome VARCHAR(25) NOT NULL,
	permissao TINYINT NOT NULL,
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE ESTILO (
	idEstilo SMALLINT PRIMARY KEY IDENTITY,
	nomeEstilo VARCHAR(20) NOT NULL,
);

CREATE TABLE ALBUM (
	idAlbum SMALLINT PRIMARY KEY IDENTITY,
	idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA (idArtista),
	nomeAlbum VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE ALBUM_ESTILO (
	idAlbumEstilo SMALLINT PRIMARY KEY IDENTITY,
	idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM (idAlbum),
	idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO (idEstilo)
);
GO