USE CATALOGO

SELECT * FROM GENERO
SELECT * FROM FILME
GO

SELECT idFilme, nomeFilme, nomeGenero FROM FILME
LEFT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero
GO

SELECT nomeFilme, nomeGenero FROM FILME
RIGHT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero
GO

SELECT nomeFilme, nomeGenero FROM FILME
INNER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero
GO

SELECT nomeFilme, nomeGenero FROM FILME
FULL OUTER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero
GO
