CREATE DATABASE CLINICA;
GO

USE CLINICA
GO

CREATE TABLE ESPECIE (
	idEspecie SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEspecie VARCHAR(50) NOT NULL
);
GO

CREATE TABLE DONO (
	idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeDono VARCHAR(25) NOT NULL,
	idade TINYINT,
	CPF CHAR(11) NOT NULL,
);
GO

CREATE TABLE ENDERECO (
	idEnd SMALLINT PRIMARY KEY IDENTITY(1,1),
	estado VARCHAR(30),
	cidade VARCHAR(30),
	rua VARCHAR(30),
	numero VARCHAR(5),
	cep char(8) NOT NULL,
);
GO

CREATE TABLE CLINICA (
	idClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEnd SMALLINT FOREIGN KEY REFERENCES ENDERECO (idEnd),
	nomeClinica VARCHAR(25) NOT NULL,
);
GO

CREATE TABLE VETERINARIO (
	idVeterinario SMALLINT PRIMARY KEY IDENTITY(1,1),
	idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA (idClinica),
	nomeVeterinario VARCHAR(25) NOT NULL,
	cpf CHAR(11) NOT NULL,
);
GO

CREATE TABLE RACA (
	idRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEspecie SMALLINT FOREIGN KEY REFERENCES ESPECIE (idEspecie),
	nomeRaca VARCHAR(30) NOT NULL,
);
GO

CREATE TABLE PET (
	idPet SMALLINT PRIMARY KEY IDENTITY(1,1),
	idRaca SMALLINT FOREIGN KEY REFERENCES RACA (idRaca),
	idDono SMALLINT FOREIGN KEY REFERENCES DONO (idDono),
	nomePet VARCHAR(35),
);
GO

CREATE TABLE ATENDIMENTO (
	idAtendimento SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO (idVeterinario),
	idPet SMALLINT FOREIGN KEY REFERENCES PET (idPet),
	dataAtedimento SMALLDATETIME NOT NULL,
);
GO