CREATE DATABASE EMPRESA;
GO

USE EMPRESA;
GO


-- TABLE PESSOA
CREATE TABLE PESSOA (
	idPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomePessoa VARCHAR(20),
);
GO

ALTER TABLE PESSOA
DROP COLUMN nomePessoa
GO

ALTER TABLE PESSOA
ADD nomePessoa VARCHAR(20) NOT NULL;
GO

ALTER TABLE PESSOA 
ADD CNH CHAR(11);
GO

-- TABLE TELEFONE
CREATE TABLE TELEFONE (
	idTelefone INT PRIMARY KEY IDENTITY(1,1),
	idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA (idPessoa),
	numeroTelefone VARCHAR(15) NOT NULL
);
GO

--TABLE EMAIL
CREATE TABLE EMAIL (
	idEmail INT PRIMARY KEY IDENTITY(1,1),
	idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA (idPessoa),
	endEmail VARCHAR(256) NOT NULL
);
GO

